//LOGIN LOGOUT REGISTER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_CREATED = "USER_CREATED";
export const USER_CREATED_FAIL = "USER_CREATED_FAIL";
export const USER_UPDATED = "USER_UPDATED";

//AUTH ACTIONS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

//POEM ACTIONS
export const GET_POEMS_SUCCESS = "GET_POEMS_SUCCESS";
export const GET_POEM_SUCCESS = "GET_POEM_SUCCESS";
export const ADD_POEM_SUCCESS = "ADD_POEM_SUCCESS";
export const DELETE_POEM_SUCCESS = "DELETE_POEM_SUCCESS";
export const UPDATE_POEM_SUCCESS = "UPDATE_POEM_SUCCESS";

//AUTHOR ACTIONS
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";

//GENRE ACTIONS
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const ADD_GENRE_SUCCESS = "ADD_GENRE_SUCCESS";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";
export const UPDATE_GENRE_SUCCESS = "UPDATE_GENRE_SUCCESS";

//ALERT ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
